I retrieved the data for financial statements and stock prices via the Yahoo Finance API.

In [20]:
pip install yfinance

Requirement already satisfied: yfinance in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.2.36)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (1.26.3)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (5.1.0)
Requirement already satisfied: appdirs>=1.4.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2023.11.17)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [21]:
!pip install yahoofinancials

Requirement already satisfied: yahoofinancials in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.20)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (2023.3.post1)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (2.31.0)
Requirement already satisfied: appdirs>=1.4.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (1.4.4)
Requirement already satisfied: frozendict>=2.3.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (4.12.2)
Requirement already satisfied: lxml>=4.9.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yahoofinancials) (5.1.0)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yahoofinancials) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yahoofinancials) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yahoofinancials) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yahoofinancials) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yahoofinancials) (2023.11.17)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip

In [16]:
import yfinance as yf
sedg = yf.Ticker("SEDG")

Fatch the data for income statements (quarter and annual) for SolarEdge

In [34]:
sedg_quarter_income_stmt = sedg.quarterly_income_stmt
sedg_quarter_income_stmt.to_csv('sedg_income_stmt.csv')

In [19]:
sedg_annual_income_stmt = sedg.income_stmt
sedg_annual_income_stmt.to_csv('sedg_annual_income_stmt.csv')

Fatch the data for income statements (quarter and annual) for Enphase Energy

In [37]:
enph = yf.Ticker("ENPH")

enph_quarter_income_stmt = enph.quarterly_income_stmt
enph_quarter_income_stmt.to_csv('enph__quarter_income_stmt.csv')

enph_annual_income_stmt = enph.income_stmt
enph_annual_income_stmt.to_csv('enph_annual_income_stmt.csv')

Fatch the data balance sheet (quarter and annual) for SolarEdge

In [36]:
sedg_quarter_balance_sheet = sedg.quarterly_balance_sheet
sedg_quarter_balance_sheet.to_csv('sedg_balance_sheet.csv')

sedg_annual_balance_sheet = sedg.balance_sheet
sedg_annual_balance_sheet.to_csv('sedg_annual_balance_sheet.csv')

Fatch the data balance sheet (quarter and annual) for Enphase Energy

In [38]:
enph_quarter_balance_sheet = enph.quarterly_balance_sheet
enph_quarter_balance_sheet.to_csv('enph__quarter_balance_sheet.csv')

enph_annual_balance_sheet = enph.balance_sheet
enph_annual_balance_sheet.to_csv('enph_annual_balance_sheet.csv')

Fatch the data for income statements (quarter and annual) for Sun Power

In [39]:
spwr = yf.Ticker("SPWR")

spwr_quarter_income_stmt = spwr.quarterly_income_stmt
spwr_quarter_income_stmt.to_csv('spwr__quarter_income_stmt.csv')

spwr_annual_income_stmt = spwr.income_stmt
spwr_annual_income_stmt.to_csv('spwr_annual_income_stmt.csv')

Fatch the data balance sheet (quarter and annual) for Sun Power

In [40]:
spwr_quarter_balance_sheet = spwr.quarterly_balance_sheet
spwr_quarter_balance_sheet.to_csv('spwr__quarter_balance_sheet.csv')

spwr_annual_balance_sheet = spwr.balance_sheet
spwr_annual_balance_sheet.to_csv('spwr_annual_balance_sheet.csv')

Fatch the data for income statements (quarter and annual) for First Solar

In [8]:
fslr = yf.Ticker("FSLR")

fslr_quarter_income_stmt = fslr.quarterly_income_stmt
fslr_quarter_income_stmt.to_csv('fslr__quarter_income_stmt.csv')

fslr_annual_income_stmt = fslr.income_stmt
fslr_annual_income_stmt.to_csv('fslr_annual_income_stmt.csv')

Fatch the data balance sheet (quarter and annual) for First Solar

In [9]:
fslr_quarter_balance_sheet = fslr.quarterly_balance_sheet
fslr_quarter_balance_sheet.to_csv('fslr__quarter_balance_sheet.csv')

fslr_annual_balance_sheet = fslr.balance_sheet
fslr_annual_balance_sheet.to_csv('fslr_annual_balance_sheet.csv')

Fatch the data stock prices for all companies

In [31]:
data = yf.download("SEDG ENPH SPWR", start="2017-01-01", end="2024-01-31")
data

[*********************100%%**********************]  3 of 3 completed

Price        Adj Close                            Close                       \
Ticker            ENPH       SEDG      SPWR        ENPH       SEDG      SPWR
Date
2017-01-03    1.050000  13.200000  4.485920    1.050000  13.200000  4.485920
2017-01-04    1.150000  14.400000  4.636542    1.150000  14.400000  4.636542
2017-01-05    1.120000  13.800000  4.669286    1.120000  13.800000  4.669286
2017-01-06    1.110000  13.750000  4.616896    1.110000  13.750000  4.616896
2017-01-09    1.110000  13.500000  4.682384    1.110000  13.500000  4.682384
...                ...        ...       ...         ...        ...       ...
2024-01-24  108.070000  70.199997  3.210000  108.070000  70.199997  3.210000
2024-01-25  106.830002  70.440002  3.280000  106.830002  70.440002  3.280000
2024-01-26  105.370003  68.839996  3.200000  105.370003  68.839996  3.200000
2024-01-29  109.169998  71.250000  3.440000  109.169998  71.250000  3.440000
2024-01-30  106.349998  69.160004  3.110000  106.349998  69.160004  3.110000

Price             High                              Low                       \
Ticker            ENPH       SEDG      SPWR        ENPH       SEDG      SPWR
Date
2017-01-03    1.050000  13.200000  4.505566    1.010000  12.550000  4.322200
2017-01-04    1.150000  14.450000  4.767518    1.050000  13.300000  4.499018
2017-01-05    1.190000  14.575000  4.728225    1.110000  13.775000  4.564506
2017-01-06    1.140000  14.000000  4.734774    1.080000  13.600000  4.610347
2017-01-09    1.110000  13.700000  4.767518    1.080000  13.150000  4.571054
...                ...        ...       ...         ...        ...       ...
2024-01-24  114.639999  73.760002  3.650000  108.050003  69.870003  3.190000
2024-01-25  110.099998  70.760002  3.290000  103.720001  65.620003  3.060000
2024-01-26  109.449997  71.459999  3.470000  104.970001  68.830002  3.170000
2024-01-29  109.440002  71.320000  3.450000  103.440002  67.169998  3.100000
2024-01-30  110.959999  72.190002  3.450000  106.260002  69.000000  3.090000

Price             Open                        Volume
Ticker            ENPH       SEDG      SPWR     ENPH     SEDG     SPWR
Date
2017-01-03    1.020000  12.550000  4.394237   445900  1123600  5370612
2017-01-04    1.090000  13.300000  4.505566   903000  1363300  7899476
2017-01-05    1.190000  14.300000  4.636542   308700   647700  7246073
2017-01-06    1.120000  13.900000  4.649640   259700   537300  2912753
2017-01-09    1.100000  13.700000  4.623445   180000   733400  2894123
...                ...        ...       ...      ...      ...      ...
2024-01-24  114.379997  73.570000  3.500000  3906200  2220700  6479900
2024-01-25  109.180000  70.599998  3.270000  3888000  3770000  4816700
2024-01-26  107.699997  71.300003  3.330000  2581900  1557000  4658900
2024-01-29  105.230003  68.300003  3.230000  3232200  2152300  4754700
2024-01-30  107.739998  70.360001  3.380000  3030500  1940000  7919500

[1780 rows x 18 columns]

In [32]:
data = yf.download("SEDG ENPH SPWR", start="2017-01-01",
                    end="2024-01-31", group_by='tickers')
data

[*********************100%%**********************]  3 of 3 completed

Ticker            ENPH                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2017-01-03    1.020000    1.050000    1.010000    1.050000    1.050000
2017-01-04    1.090000    1.150000    1.050000    1.150000    1.150000
2017-01-05    1.190000    1.190000    1.110000    1.120000    1.120000
2017-01-06    1.120000    1.140000    1.080000    1.110000    1.110000
2017-01-09    1.100000    1.110000    1.080000    1.110000    1.110000
...                ...         ...         ...         ...         ...
2024-01-24  114.379997  114.639999  108.050003  108.070000  108.070000
2024-01-25  109.180000  110.099998  103.720001  106.830002  106.830002
2024-01-26  107.699997  109.449997  104.970001  105.370003  105.370003
2024-01-29  105.230003  109.440002  103.440002  109.169998  109.169998
2024-01-30  107.739998  110.959999  106.260002  106.349998  106.349998

Ticker                    SEDG                                              \
Price        Volume       Open       High        Low      Close  Adj Close
Date
2017-01-03   445900  12.550000  13.200000  12.550000  13.200000  13.200000
2017-01-04   903000  13.300000  14.450000  13.300000  14.400000  14.400000
2017-01-05   308700  14.300000  14.575000  13.775000  13.800000  13.800000
2017-01-06   259700  13.900000  14.000000  13.600000  13.750000  13.750000
2017-01-09   180000  13.700000  13.700000  13.150000  13.500000  13.500000
...             ...        ...        ...        ...        ...        ...
2024-01-24  3906200  73.570000  73.760002  69.870003  70.199997  70.199997
2024-01-25  3888000  70.599998  70.760002  65.620003  70.440002  70.440002
2024-01-26  2581900  71.300003  71.459999  68.830002  68.839996  68.839996
2024-01-29  3232200  68.300003  71.320000  67.169998  71.250000  71.250000
2024-01-30  3030500  70.360001  72.190002  69.000000  69.160004  69.160004

Ticker                   SPWR
Price        Volume      Open      High       Low     Close Adj Close   Volume
Date
2017-01-03  1123600  4.394237  4.505566  4.322200  4.485920  4.485920  5370612
2017-01-04  1363300  4.505566  4.767518  4.499018  4.636542  4.636542  7899476
2017-01-05   647700  4.636542  4.728225  4.564506  4.669286  4.669286  7246073
2017-01-06   537300  4.649640  4.734774  4.610347  4.616896  4.616896  2912753
2017-01-09   733400  4.623445  4.767518  4.571054  4.682384  4.682384  2894123
...             ...       ...       ...       ...       ...       ...      ...
2024-01-24  2220700  3.500000  3.650000  3.190000  3.210000  3.210000  6479900
2024-01-25  3770000  3.270000  3.290000  3.060000  3.280000  3.280000  4816700
2024-01-26  1557000  3.330000  3.470000  3.170000  3.200000  3.200000  4658900
2024-01-29  2152300  3.230000  3.450000  3.100000  3.440000  3.440000  4754700
2024-01-30  1940000  3.380000  3.450000  3.090000  3.110000  3.110000  7919500

[1780 rows x 18 columns]

In [33]:
data.to_csv('historical_data.csv')

In [2]:
pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 831.8 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas-datareader) (5.1.0)
Requirement already satisfied: pandas>=0.23 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas-datareader) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas-datareader) (2.31.0)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.23->pandas-datareader) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.23->pandas-datareader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.23->pandas-datareader) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.19.0->pandas-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.19.0->pandas-datareader) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.19.0->pandas-datareader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.19.0->pandas-datareader) (2023.11.17)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.10.0

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
plt.style.use("fivethirtyeight")
%matplotlib inline

# For reading stock data from yahoo
from pandas_datareader.data import DataReader
import yfinance as yf
from pandas_datareader import data as pdr

yf.pdr_override()

# For time stamps
from datetime import datetime


# The tech stocks we'll use for this analysis
tech_list = ['SEDG', 'ENPH', 'SPWR', 'FSLR']

# Set up End and Start times for data grab
tech_list = ['SEDG', 'ENPH', 'SPWR', 'FSLR']

end = datetime.now()
start = "2017-01-01"

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [SEDG, ENPH, SPWR, FSLR]
company_name = ["Solaredge", "Enphase Energy", "SunPower", "First Solar"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
df.tail(10)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,company_name
Date,,,,,,,
2024-01-22,148.490005,159.229996,147.940002,149.910004,149.910004,2747400,First Solar
2024-01-23,153.880005,157.669998,149.800003,151.460007,151.460007,1773200,First Solar
2024-01-24,153.539993,154.130005,148.250000,148.869995,148.869995,1600500,First Solar
2024-01-25,150.190002,151.279999,145.910004,149.229996,149.229996,1521200,First Solar
2024-01-26,149.059998,150.649994,147.419998,147.830002,147.830002,1148600,First Solar
2024-01-29,146.990005,149.330002,144.330002,149.300003,149.300003,1652700,First Solar
2024-01-30,148.399994,150.750000,146.490005,149.029999,149.029999,1354100,First Solar
2024-01-31,149.000000,154.919998,146.050003,146.300003,146.300003,2419000,First Solar
2024-02-01,149.779999,154.309998,146.809998,147.889999,147.889999,2311900,First Solar
2024-02-02,143.979996,144.020004,138.830002,141.820007,141.820007,2619600,First Solar

In [11]:
df.to_csv('stock_prices.csv')

In [5]:
# The tech stocks we'll use for this analysis
tech_list = ['SEDG']

# Set up End and Start times for data grab
tech_list = ['SEDG']

end = datetime.now()
start = "2017-01-01"

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [SEDG]
company_name = ["Solaredge"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
df.tail(10)

df.to_csv('stock_prices_sedg.csv')

[*********************100%%**********************]  1 of 1 completed

In [6]:
# The tech stocks we'll use for this analysis
tech_list = ['ENPH']

# Set up End and Start times for data grab
tech_list = ['ENPH']

end = datetime.now()
start = "2017-01-01"

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [ENPH]
company_name = ["Enphase Energy"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
df.tail(10)

df.to_csv('stock_prices_enph.csv')

[*********************100%%**********************]  1 of 1 completed

In [7]:
# The tech stocks we'll use for this analysis
tech_list = ['SPWR']

# Set up End and Start times for data grab
tech_list = ['SPWR']

end = datetime.now()
start = "2017-01-01"

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [SPWR]
company_name = ["SunPower"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
df.tail(10)

df.to_csv('stock_prices_spwr.csv')

[*********************100%%**********************]  1 of 1 completed

In [12]:
# The tech stocks we'll use for this analysis
tech_list = ['FSLR']

# Set up End and Start times for data grab
tech_list = ['FSLR']

end = datetime.now()
start = "2017-01-01"

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [FSLR]
company_name = ["First Solar"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
df.tail(10)

df.to_csv('stock_prices_fslr.csv')

[*********************100%%**********************]  1 of 1 completed